---
apiVersion: v2
name: owm-exporter
description: An OpenWeatherMap Prometheus exporter chart
version: 1.0.2
appVersion: 1.0.2
type: application
maintainers:
  - name: Richard Kosegi
    email: richard.kosegi@gmail.com
